- name: AWS CLI | Create .aws dir
  become: true
  become_user: "{{ aws_config_user }}"
  file:
    path: "/home/{{ aws_config_user }}/.aws"
    state: directory
    owner: "{{ aws_config_user }}"
    group: "{{ aws_config_user }}"

- name: AWS CLI | Create config
  become: true
  become_user: "{{ aws_config_user }}"
  template:
    src: config.j2
    dest: "/home/{{ aws_config_user }}/.aws/config"
    mode: '0640'
